### ISSUE TITLE
Does your method apply to a 3R-R-R-R-R configuration robotic arm?

### ISSUE THREAD

**Issue by Sunday377** [aelias36/stereo-sew#1]

**Comment by aelias36** [comment]
Yes, the subproblem decomposition approach can solve IK for a 3R-R-R-R-R robot parameterized by SEW angle.

Even without considering parallel or intersecting axes, we can solve a general 7R manipulator using 2D search.

But since we do have a 3R joint, we can solve IK with 1D search rather than 2D search.

Assuming you are labeling the joints as 3R^S-R^E-R-R-R^W, the solution method is very similar to the 3R^S-R^E
-2R-R^W case. Given theta_S, you can find the location of the elbow, and then find (q_5, q_6, q_7) using Subproblem 5. After finding the zeros of the error (which is a function of theta_S), you can find q_4 with Subproblem 1 and (q_1, q_2, q_3) with Subproblem 2 and Subproblem 1.

(In case you prefer to parameterize by one joint angle rather than by SEW angle, fixing joints 4, 5, 6, or 7 results in a 3R-R-R-R robot which can be solved in closed form.)

Let me know if you need any more help deriving or implementing this IK solution.

**Comment by aelias36** [comment]
Yes, the subproblem decomposition approach can solve IK for a 3R-R-R-R-R robot parameterized by SEW angle.

Even without considering parallel or intersecting axes, we can solve a general 7R manipulator using 2D search.

But since we do have a 3R joint, we can solve IK with 1D search rather than 2D search.

Assuming you are labeling the joints as 3R^S-R^E-R-R-R^W, the solution method is very similar to the 3R^S-R^E
-2R-R^W case. Given theta_S, you can find the location of the elbow, and then find (q_5, q_6, q_7) using Subproblem 5. After finding the zeros of the error (which is a function of theta_S), you can find q_4 with Subproblem 1 and (q_1, q_2, q_3) with Subproblem 2 and Subproblem 1.

(In case you prefer to parameterize by one joint angle rather than by SEW angle, fixing joints 4, 5, 6, or 7 results in a 3R-R-R-R robot which can be solved in closed form.)

Let me know if you need any more help deriving or implementing this IK solution.
